# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8dfb08219af561d6761ad2f9b891702f"
name = "Simple gifting"
handle = "simple-gifting"
application_url = "https://focused-candles-telling-establish.trycloudflare.com"
embedded = true

[access]
admin.direct_api_mode = "offline"
admin.embedded_app_direct_api_access = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes,read_orders,write_orders"
use_legacy_install_flow = false

[auth]
redirect_urls = ["https://focused-candles-telling-establish.trycloudflare.com/auth/callback", "https://focused-candles-telling-establish.trycloudflare.com/auth/shopify/callback", "https://focused-candles-telling-establish.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://focused-candles-telling-establish.trycloudflare.com/proxy"
subpath = "gifting"
prefix = "apps"
