# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8dfb08219af561d6761ad2f9b891702f"
name = "Simple gifting"
handle = "simple-gifting"
application_url = "https://affordable-metres-technologies-tablets.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "products/create" ]
  uri = "/webhooks/products/create"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://affordable-metres-technologies-tablets.trycloudflare.com/auth/callback", "https://affordable-metres-technologies-tablets.trycloudflare.com/auth/shopify/callback", "https://affordable-metres-technologies-tablets.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false

[app_proxy]
url = "https://affordable-metres-technologies-tablets.trycloudflare.com/proxy"
subpath = "gifting"
prefix = "apps"
